### ISSUE TITLE
Maven build fails with Java 1.9 EA

### ISSUE THREAD

**Issue by vruusmann** [openscoring/openscoring#5]
It has been reported via e-mail that the project cannot be built using Java 1.9 EA due to the following compilation error:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project openscoring-service: Compilation failure
/home/german/openscoring/openscoring-service/src/main/java/org/openscoring/service/CsvUtil.java:[172,31] error: incompatible types: LinkedHashMap<String,CAP#1> cannot be converted to Map<String,Object>
```

The project [builds correctly with Java 1.7 and 1.8](https://travis-ci.org/jpmml/openscoring).
